In [1]:
import numpy as np

In [3]:
revenue = np.array([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]])
revenue

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [4]:
#US dollars to INR
inr = 75 * revenue
inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [7]:
flowers = np.array([[50, 60, 25], [10, 13, 5], [40, 70, 52]])
price_per_unit = np.array([20, 30, 15])
sales = np.dot(price_per_unit, flowers)

In [8]:
sales

array([1900, 2640, 1430])